### ISSUE TITLE
contributor guidelines

### ISSUE THREAD

**Issue by cgoldberg** [cicada-load/cicada#2]
We need to discuss a (lightweight) process and guidelines for contribution.

The standard way to do this is to create a file named "CONTRIBUTING" in the repo root.  It will contain our contributor guidelines.

We should add a group of core maintainers to the org that have merge access (populated from volunteers in this thread).  While they have access to merge, it is only used for merging pull requests (never push directly to master without a PR).  Maintainers will follow the same model described below for all contributors:

To get code into cicada's master, you would:

* fork the repo
* make changes in your fork (in a feature branch)
* create a pull request to land the branch into cicada/master
* the pull request must go through code review (anyone is encouraged to do initial reviews)
* once a PR looks in acceptable shape, it needs signoff (a :+1: comment from 2 maintainers)
* once it has been thumbed up twice, a maintainer will merge the branch to master on the contributor's behalf.

Does that sound reasonable for a basic working process?

btw, 2 things to mention:

* the codebase is far from PEP8 compliant.  This is fine to start, but we should move towards a more standard Python style.  Once we get closer to that goal, we can add linting (pep8, flake8, pylint, etc) to our CI process.

* automated are necessary, but currently the codebase only contains a small set of functional/acceptance tests, but lacks unit tests.  I think this is ok to start with, but let's not build much more technical debt.  Once things get rolling, we may want to measure code coverage in CI, and require tests accompanying new pull requests.  Once we have a small body of tests to run in CI, we should run CI against every PR and gate merges on failing tests.

thoughts?

**Comment by jmelfi** [comment]
@cgoldberg I agree with all that was said here.  I think that 2 maintainers is a good start and this should be light enough to not need constant work on this.

I think the only thing that I would want required is that the current tests pass and any new ones do as well.

We should definitely define how we want code created and start moving to PEP8.

**Comment by jinxcat** [comment]
Some comments:
- we should prioritise making the codebase PEP8 so we can include it in the automated tests (not proposing a specific priority, just that it goes up on the list of priorities, so it is kept in our radar). I believe it can be completed fairly quickly if we are set on completing it.
- Creating tests for new code should be addressed in the guidelines in my opinion.
- passing automated tests should be mentioned. A PR not passing tests probably can not even be reviewed yet, other than to address the failing tests.
- 2 maintainers clearing a PR seems fine, as long as we are vigilant about actually reviewing code :)

**Comment by deniscostadsc** [comment]
> we should prioritise making the codebase PEP8 so we can include it in the automated tests (not proposing a specific priority, just that it goes up on the list of priorities, so it is kept in our radar). I believe it can be completed fairly quickly if we are set on completing it.

This should be a issue, and should be fixed as soon as possible. This is going to be hard we postpone this. I can do that.

> Creating tests for new code should be addressed in the guidelines in my opinion.

Agreed.

> Passing automated tests should be mentioned. A PR not passing tests probably can not even be reviewed yet, other than to address the failing tests.

This is easy to be done. And I think is going to be here https://github.com/cicada-load/cicada/issues/1

> 2 maintainers clearing a PR seems fine, as long as we are vigilant about actually reviewing code :)

Agreed.
