### ISSUE TITLE
remove all "locust" branding from README and docs

### ISSUE THREAD

**Issue by cgoldberg** [cicada-load/cicada#3]
We need to change things over to "Cicada" wherever "Locust" is mentioned.

**Comment by jmelfi** [comment]
It appears that we need a site that can be used to host the documentation for it to be reasonable to have all the locust naming removed.  I can start working on this to finish it up once this is decided on.

**Comment by deniscostadsc** [comment]
Just after we deploy cicada documentation somewhere, right?

**Comment by jmelfi** [comment]
yes, after we deploy the documentation somewhere.  We could do that via a gh-pages branch for the docs here or some other hosting service such as ReadTheDocs.
