### ISSUE TITLE
Priorities

### ISSUE THREAD

**Issue by smrpr** [cicada-load/cicada#5]
I think we should set some priorities for this project to move on. Should we start with the open MR's in Locust?

My vote would be Python 3 support, and start from there.

Things already discussed:
* Python 3 support
* PR process (tests, Travis-CI?)
* Community guidelines

**Comment by jinxcat** [comment]
I think we need a list of possible matters to prioritise over, and then set them in order :)

For example, I agree with the above, but setting a PR process takes precedence. And that includes test suite, CI, process rules/guidelines.

**Comment by jmelfi** [comment]
@smrpr I agree that Python 3 support is a very big need.

I concur though with @jinxcat that PR process, contributor guidelines, CI integration and testing must come first.

**Comment by jmelfi** [comment]
I think our best option is to gather what are desired changes and determine their priority.  We can then breakdown and set milestones, attach issues to them and then begin working as a group to tackle these.  I think if we could communicate this as well, it would help bolster support with a clear vision for improvement.

**Comment by zvxr** [comment]
@smrpr Python 3 support definitely seems like a huge need/request.

@jmelfi This sounds like a great way to go. Since there will be a good number of people working on the project, it might be a good idea to determine process and recording in the README as far as branching and merging goes (by feature? By point release?). It might also be good to start a HISTORY.md to note changes from version to version.

**Comment by jmelfi** [comment]
@zvxr I like the idea of HISTORY.md for a change-log.  I think that we definitely need to have a set way of contributing that I believe was brought up in #2 briefly.  It would be important to capture this and have it referenced by the README.md.

**Comment by cgoldberg** [comment]
I can work on the CONTRIBUTING doc, but not for a few days.  If someone wants to beat me to it, go ahead and create a PR.  If nobody can, I'll pick it up this weekend.

**Comment by jinxcat** [comment]
Shall we make a list of priorities so that we can vote on them afterwards?
@smrpr : can you update the issue description with the ones mentioned already?

**Comment by justiniso** [comment]
@jinxcat I think we should document our priorities as issues with labels. We all sort of have a vague idea of which ones we want to tackle first (e.g. test coverage + CI, python 3 support, community guidelines). Feel free to disagree, but I'm personally against too much process and don't think we need to vote on which issues people should work on. I think people should feel free to tackle whichever issues they want and in the issue just say something along the lines of:

- "working on this"
- "can get to this next week, but someone else can take it in the meantime"
- "can't do this, but here's how I think it should be done..."

**Comment by smrpr** [comment]
I updated my first post with what we've discussed but I agree the best way would be opening different issues to tackle these topics separately.

**Comment by jinxcat** [comment]
Can we please add to priorities:
- Bringing codebase to PEP8 (as discussed here: https://github.com/cicada-load/cicada/issues/2#issuecomment-198007179 )
- Test coverage (100%, or as close to that as possible?)

**Comment by jinxcat** [comment]
@justiniso : my intention is not to form a cemented list of priorities that need to happen in that order, but more like a list of tasks that need to be tackled... also, to identify interdependencies. I hope it doesn't add "too much process", and I definitely understand how that can be counter-productive. Main idea is to have a list of things that we all agree in some degree need to be done, and we tackle all of them, without forgetting any.
