### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jinxcat** [cicada-load/cicada#6]
Make the project work under python 3, without errors and/or warnings

**Comment by jmelfi** [comment]
:+1:

**Comment by cgoldberg** [comment]
The current PR that implements Python 3 compatibility uses the six library and other tricks to make a single codebase that is compatible with both Python2.7 and Python3.x.  Given the current state of Python, I think this is the right way to approach it that will be useful for the most users.

just to play devil's advocate...

Another option is to drop Python 2.6/2.7 compatibility and port to Python 3 only.  This would make the code easier to test and maintain, and make future contribution easier.  I don't personally think this is the way to go, but am interested if anyone has thoughts on this.  Right at the start of this new project fork would be an ideal time to make a huge switch like that.

**Comment by jinxcat** [comment]
I would be hesitant to drop support for 2.6/2.7 as well... as long as it does not jeopardise the support for 3.x.

**Comment by zvxr** [comment]
I also would be hesitant dropping support for 2.6/2.7. Python2 is still widely used. It would be unfortunate to put users in the position of having to use either locust for Python2 (with a frozen feature set) or cicada for Python3 (with a actively developed feature set).

**Comment by jmelfi** [comment]
@cgoldberg @jinxcat @zvxr I concur that dropping 2.6 python support isn't the best idea.  I **think** we could make a reasonable position to drop 2.6 support and only maintain 2.7 python.  This would let us go to python 3 and keep our python 2 base small.

Most users would install locust in a virtualenv and this is not a problem to install/setup a python 2.7 set.  Current OS distros default to 2.7 at least and some now push python 3.

Would this be a reasonable halfway point?  I know that the difference between 2.6 and 2.7 isn't huge but perhaps the small change in scope size would be beneficial?

**Comment by zvxr** [comment]
That certainly sounds reasonable (maintaining only python 2.7).

**Comment by jinxcat** [comment]
I agree with the statement about dropping 2.6 and focusing on 3.x and 2.7.
