### ISSUE TITLE
Decide on fork name

### ISSUE THREAD

**Issue by jinxcat** [cicada-load/cicada#7]
In 2 steps:

- Nominate names
- Vote on proposed names

Nominated names:
- akris
- cicada
- locust2

**Comment by jmelfi** [comment]
I have no issues with Cicada but I'll put pmdarrow's other recommendation of **arkis**.

+1 for Arkis

**Comment by cgoldberg** [comment]
+1 for cicada

**Comment by cgoldberg** [comment]
@jmelfi 
what does arkis refer to?  The only mention of it I can find is that it's the name of an Icelandic architectural business :P

otoh, a cicada is a well-known insect that swarms and is often confused with the locust

**Comment by jinxcat** [comment]
@cgoldberg : It's "akris" and it is the (ancient?) greek name for a locust.

+1 for akris btw from me

**Comment by justiniso** [comment]
Nominations:

- akris
- cicada
- locust2 :stuck_out_tongue: 

My vote:

+1 for cicada, I think it's easier to draw the mental link to locust. You need to explain what akris means and it's not as easy to remember/spell imo.

**Comment by vividhsv** [comment]
+1 for Arkis

**Comment by justiniso** [comment]
@vividhsv it's actually "akris" not "arkis." I definitely don't want to get caught up on the name too much, but 2/4 of the people in this thread have already misspelled it, which is kind of a red flag to me. Open to other non-insect names too, I just want to stay away from anything that's confusing or so easily misspelled.

**Comment by jinxcat** [comment]
Justin poses a proper argument :/ 

I just checked on something else though:
https://github.com/search?utf8=%E2%9C%93&q=cicada
there's 127 repos returned when searching for "cicada"

**Comment by cjsimpson** [comment]
I like cicada

**Comment by oskar-d** [comment]
I think cicada sounds good, it has a clear relation to the original locust. And it's something most people know what it is.

**Comment by djonsson** [comment]
+1 for cicada
