### ISSUE TITLE
Chat?

### ISSUE THREAD

**Issue by jmelfi** [cicada-load/cicada#9]
The old project had gitter.  That would be easy to setup and integrate.  I could do that if given the link and add it to the documentation [PR open](#8).

**Comment by cgoldberg** [comment]
is gitter any good?  better than slack?

**Comment by justiniso** [comment]
I've used both, but they tackle different things. Glitter is more for the general public to join and ask questions (think pretty IRC client). Slack would be more for chat among a core group of people, e.g. the maintainers. We should have a public glitter, but I don't really care which we use internally. BTW I made a slack already, feel free to join: https://cicadaload.slack.com

**Comment by jmelfi** [comment]
@justiniso I agree that Gitter is quite good for public chat to freely join/leave.  I tried to join the slack channel but was told that open signup wasn't enabled.  It appears that an invitation is needed currently.

**Comment by jinxcat** [comment]
@jmelfi an invitation should be easy to get :)

My reasoning for opting for slack is that I pretty much have slack open 24/7, so it is zero hassle to have another team open. It has been criticised lately, but I am hesitant to (personally) idle on irc in any capacity.
